const ROUTES = {
  ROOT: "/",
  ABOUT: "/about",
  GALLERY: "/gallery",
  COMMENT: "/comment",
  CONTACT: "/contact",
  MENU: {
    MANGAL: "/menu-mangal",
    CHEF: "/menu-chef",
    SHUSI: "/menu-shusi",
  },
  TABLE: "/table",
  DISH: "/dish",
  CART: "/cart",
  ADD_COMMENT: "/add-comment",
  FAV_DISH: "/fav-dish",
  DISH_DETAILS: "/dish-info",
  SIGNUP: "/signup",
  LOGIN: "/login",
  USER_PROFILE: "/user-info",
  EDIT_USER: "edit-user",
  CREATE_CARD: "/create-card",
  EDIT_CARD: "/edit-card",
  SANDBOX: "/sandbox",
};

export const SANDBOX_ROUTES = {
  COMPONENT: "component",
  TEMPLATE: "template",
  LOGIC: "logic",
  STYLES: "styles",
  LIFECYCLE: "lifecycle-hook",
  INITIAL: "initial",
  USE_STATE: "use-state-cycle",
  DID_MOUNT: "componentDidMount",
  DID_UPDATE: "useEffectDidUpdate",
  WILL_UNMOUNT: "useEffectWillUnmount",
  NO_DEPENDENCIES: "no-dependencies",
  LIFECYCLE_EXE: "exe",
  CUSTOM: "custom",
  CUSTOM_COUNTER: "counter",
  CUSTOM_NAME: "name",
  MEMOIZATION: "memoization",
  USECALLBACK: "useCallback",
  USEMEMO: "useMemo",
  CONTEXT: "context",
  NAME: "name",
  SNACK: "snack",
  FORM: "form",
};

export default ROUTES;
